version: "3.8"

services:
   namenode:
      image: apache/hadoop:3.3.6
      hostname: namenode
      container_name: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
      env_file:
        - ./config-hadoop
      environment:
        - ENSURE_NAMENODE_DIR=/tmp/hadoop-hadoop/dfs/name

   datanode:
      image: apache/hadoop:3.3.6
      hostname: datanode
      container_name: datanode
      command: ["hdfs", "datanode"]
      env_file:
        - ./config-hadoop

   resourcemanager:
      image: apache/hadoop:3.3.6
      hostname: resourcemanager
      container_name: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config-hadoop

   nodemanager:
      image: apache/hadoop:3.3.6
      hostname: nodemanager
      container_name: nodemanager
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config-hadoop